---
- hosts: Manager
  user: ubuntu
  become: yes
  gather_facts: yes


  tasks:

    - name: Apply rook deployment ceph
      command: "{{ item }}"
      with_items:
      - kubectl create -f /var/tmp/rook/deploy/examples/crds.yaml -f /var/tmp/rook/deploy/examples/common.yaml -f /var/tmp/rook/deploy/examples/operator.yaml
      - kubectl create -f /var/tmp/rook/deploy/examples/cluster.yaml

    - name: Sleep for 120 seconds
      wait_for:
         delay: 120
         timeout: 0

    - name: Create the dashboard for Ceph to access through the NodePort Service.
      command: kubectl apply -f /var/tmp/dashboard-external-https.yaml

    - name: Create the ceph tool pod for troubleshooting
      command: kubectl create -f /var/tmp/rook/deploy/examples/toolbox.yaml
      
    - name: Change the svc to NodePort
      command: kubectl patch svc rook-ceph-mgr-dashboard-external-https -n rook-ceph --type='json' -p '[{"op":"replace","path":"/spec/type","value":"NodePort"},{"op":"replace","path":"/spec/ports/0/nodePort","value":32528}]'
      
    - name: Sleep for 30 seconds
      wait_for:
         delay: 30
         timeout: 0

    - name: To get the Ceph admin credentials
      shell: kubectl -n rook-ceph get secret rook-ceph-dashboard-password -o jsonpath="{['data']['password']}" | base64 --decode
      register: creds

    - name: Output the variable
      debug:
       msg: "{{creds.stdout}}"

    - name: save locally
      local_action:
         module: copy
         content: "{{ creds.stdout_lines }}"
         dest: /terraform/ansible/rook-ceph/ceph-creds.txt
